Repository rjbohlender/IBDMap, pull requests merged in 2025-09, with the labels that each got.

#25 Fix permutation column offsets and add coverage
  IBDReduce/ibdreduce_v3.py
  tests/data/sample_chr1_run1.txt
  tests/test_permutation_columns.py
Labels: codex

#32 Update ibdreduce_v3.py to allow for a matrix phenotype file or 2 column file
  IBDReduce/ibdreduce_v3.py
Labels: enhancement

#29 uploaded the requirements.txt file
  IBDReduce/requirements.txt
Labels: enhancement

#28 Update README.md
  README.md
Labels: documentation

#33 Accidental bug in phenotype parser
  IBDReduce/ibdreduce_v3.py
Labels: bug
